definitions:
  models.Article:
    properties:
      ID:
        type: integer
      author:
        type: string
      body:
        type: string
      created_at:
        type: string
      title:
        type: string
    type: object
  request.Create:
    properties:
      author:
        maxLength: 50
        minLength: 4
        type: string
      body:
        minLength: 20
        type: string
      title:
        minLength: 8
        type: string
    required:
    - author
    - body
    - title
    type: object
  response.Index:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Article'
        type: array
      meta:
        $ref: '#/definitions/utils.PaginationMeta'
    type: object
  utils.GeneralResponse:
    properties:
      message:
        type: string
    type: object
  utils.PaginationMeta:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  utils.ValidatorResponse:
    properties:
      message:
        additionalProperties:
          type: string
        type: object
    type: object
info:
  contact: {}
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Get articles by body and title with pagination
      parameters:
      - description: search
        in: query
        name: search
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Index'
      summary: Search articles
      tags:
      - Articles
    post:
      consumes:
      - application/json
      description: Create new article,
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Create'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ValidatorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.GeneralResponse'
      summary: Create article
      tags:
      - Articles
swagger: "2.0"
